[tool.poetry]
name = "librarysystem"
version = "0.1.0"
description = ""
authors = ["Andrew Henkel <search1230@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9.*, <=3.10.*"
Django = "~3.2.13"
psycopg2 = "^2.9"
django-crispy-forms = "~1.14"
python-decouple = "^3.6"
djangorestframework = "~3.13.1"
requests-oauthlib = "~1.3"

[tool.poetry.dev-dependencies]
pylint = "^2.14.4"
pylint-django = "^2.5.3"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
