# Generated by Django 3.2.14 on 2022-07-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_student_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.CharField(max_length=6, unique=True, verbose_name='student ID'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='signup.student'),
        ),
    ]
