# Generated by Django 3.2.14 on 2022-07-12 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_class_periods_and_sign_ups'),
    ]

    operations = [
        migrations.AddField(
            model_name='classperiodsignup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date signed up'),
        ),
    ]
