# Generated by Django 3.2.14 on 2022-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_add_date_signed_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classperiodsignup',
            old_name='date',
            new_name='date_signed_up',
        ),
        migrations.AddField(
            model_name='classperiodsignup',
            name='attendance_confirmed',
            field=models.BooleanField(default=False, verbose_name='attendance confirmed'),
        ),
        migrations.AddField(
            model_name='classperiodsignup',
            name='date_attendance_confirmed',
            field=models.DateTimeField(null=True, verbose_name='date attendance was confirmed'),
        ),
    ]
